# Arbor: a config-driven booking engine
# Copyright (C) 2026 Alban Billiette and the Arbor contributors
# SPDX-License-Identifier: AGPL-3.0-or-later

"""Ported three-vertical seed data (transcribed verbatim from
frontend/src/api/seed/{fleet,oneToOne,group}.ts). Pure data, the assembler in
seed.py turns each vertical into DB rows."""

# --- shared helpers --------------------------------------------------------
# Some verticals book a whole DAY rather than a time-of-day slot: one venue,
# one family, one date. `seed_config._grid` takes the same branch for any
# service whose duration is >= 1440 minutes, a single 00:00 start per day,
# so the calendar reads as a date picker rather than a timetable.



DEFAULT_VERTICAL = "fleet"

VERTICALS = {
    "fleet": {
        "verticalId": "fleet",
        "bookingModel": "unit_selection",
        "currency": "EUR",
        "baseTz": "Europe/Warsaw",
        "categories": [
            {"id": "economy", "label": "Economy"},
            {"id": "suv", "label": "SUV"},
            {"id": "van", "label": "Van"},
            {"id": "electric", "label": "Electric"},
            {"id": "luxury", "label": "Luxury"},
        ],
        "providers": [
            {
                "name": "Vistula Auto",
                "tagline": "City rentals, no queues",
                "bio": "Family-run rental desk two minutes from Warsaw Central. Same-day pickup, transparent pricing, and a fleet kept under three years old.",
                "categoryId": "economy",
                "city": "Warsaw",
                "country": "Poland",
                "lat": 52.2297,
                "lng": 21.0122,
                "publicCode": "VISTULA-4471",
                "rating": 4.7,
                "reviewCount": 318,
                "links": [
                    {"label": "Website", "url": "https://example.com/vistula"},
                    {"label": "Terms", "url": "https://example.com/vistula/terms"},
                ],
            },
            {
                "name": "Nord Fleet",
                "tagline": "Coastal SUVs & 4x4s",
                "bio": "Rugged vehicles for the Tricity and beyond. Roof boxes and child seats included on request.",
                "categoryId": "suv",
                "city": "Gdańsk",
                "country": "Poland",
                "lat": 54.352,
                "lng": 18.6466,
                "publicCode": "NORD-2210",
                "rating": 4.5,
                "reviewCount": 142,
                "links": [],
            },
            {
                "name": "Kraków Renta",
                "tagline": "Budget cars, old-town pickup",
                "bio": "Economy hatchbacks collected steps from the Kazimierz district.",
                "categoryId": "economy",
                "city": "Kraków",
                "country": "Poland",
                "lat": 50.0647,
                "lng": 19.945,
                "publicCode": "KRK-8890",
                "rating": 4.3,
                "reviewCount": 96,
                "links": [],
            },
            {
                "name": "Odra Motors",
                "tagline": "Vans & movers",
                "bio": "Cargo and passenger vans for house moves and crew transport.",
                "categoryId": "van",
                "city": "Wrocław",
                "country": "Poland",
                "lat": 51.1079,
                "lng": 17.0385,
                "publicCode": "ODRA-5560",
                "rating": 4.6,
                "reviewCount": 74,
                "links": [],
            },
            {
                "name": "Baltic EV",
                "tagline": "All-electric fleet",
                "bio": "Zero-emission rentals with free charging on the first day.",
                "categoryId": "electric",
                "city": "Gdańsk",
                "country": "Poland",
                "lat": 54.372,
                "lng": 18.638,
                "publicCode": "BALT-7788",
                "rating": 4.8,
                "reviewCount": 205,
                "links": [],
            },
            {
                "name": "Piast Cars",
                "tagline": "Executive & luxury",
                "bio": "Premium saloons with chauffeur option for business travel.",
                "categoryId": "luxury",
                "city": "Poznań",
                "country": "Poland",
                "lat": 52.4064,
                "lng": 16.9252,
                "publicCode": "PIAST-3301",
                "rating": 4.9,
                "reviewCount": 61,
                "links": [],
            },
            {
                "name": "Tatra Wheels",
                "tagline": "Mountain-ready SUVs",
                "bio": "Winter tyres as standard from October. Ski racks available.",
                "categoryId": "suv",
                "city": "Kraków",
                "country": "Poland",
                "lat": 50.0619,
                "lng": 19.9368,
                "publicCode": "TATRA-6642",
                "rating": 4.4,
                "reviewCount": 88,
                "links": [],
            },
        ],
        "demoServices": [
            {
                "name": "Compact class",
                "description": "Nimble city cars, easy to park, light on fuel.",
                "slotDurationMinutes": 1440,
                "minSlotsPerBooking": 1,
                "maxSlotsPerBooking": 14,
                "priceMinorUnits": 4200,
                "cancellationCutoffHours": 48,
                "grid": {"daysBack": 28, "daysForward": 56, "startTimes": [{"hour": 0, "minute": 0}]},
                "resources": [
                    {
                        "name": "Unit C-4471",
                        "description": "Volkswagen Polo",
                        "capacity": 1,
                        "attributes": [
                            {"label": "Transmission", "value": "Manual"},
                            {"label": "Seats", "value": "5"},
                            {"label": "Fuel", "value": "Petrol"},
                            {"label": "Doors", "value": "5"},
                            {"label": "Bags", "value": "2"},
                        ],
                    },
                    {
                        "name": "Unit C-4472",
                        "description": "Toyota Yaris",
                        "capacity": 1,
                        "attributes": [
                            {"label": "Transmission", "value": "Automatic"},
                            {"label": "Seats", "value": "5"},
                            {"label": "Fuel", "value": "Hybrid"},
                            {"label": "Doors", "value": "5"},
                            {"label": "Bags", "value": "2"},
                        ],
                    },
                    {
                        "name": "Unit C-4473",
                        "description": "Škoda Fabia",
                        "capacity": 1,
                        "attributes": [
                            {"label": "Transmission", "value": "Manual"},
                            {"label": "Seats", "value": "5"},
                            {"label": "Fuel", "value": "Diesel"},
                            {"label": "Doors", "value": "5"},
                            {"label": "Bags", "value": "3"},
                        ],
                    },
                    {
                        "name": "Unit C-4474",
                        "description": "Ford Fiesta",
                        "capacity": 1,
                        "attributes": [
                            {"label": "Transmission", "value": "Manual"},
                            {"label": "Seats", "value": "5"},
                            {"label": "Fuel", "value": "Petrol"},
                            {"label": "Doors", "value": "3"},
                            {"label": "Bags", "value": "2"},
                        ],
                    },
                    {
                        "name": "Unit C-4475",
                        "description": "Hyundai i20",
                        "capacity": 1,
                        "attributes": [
                            {"label": "Transmission", "value": "Automatic"},
                            {"label": "Seats", "value": "5"},
                            {"label": "Fuel", "value": "Petrol"},
                            {"label": "Doors", "value": "5"},
                            {"label": "Bags", "value": "2"},
                        ],
                    },
                ],
            },
            {
                "name": "SUV class",
                "description": "Higher ride, more boot space, all-weather grip.",
                "slotDurationMinutes": 1440,
                "minSlotsPerBooking": 1,
                "maxSlotsPerBooking": 14,
                "priceMinorUnits": 7500,
                "cancellationCutoffHours": 48,
                "grid": {"daysBack": 28, "daysForward": 56, "startTimes": [{"hour": 0, "minute": 0}]},
                "resources": [
                    {
                        "name": "Unit S-3310",
                        "description": "Toyota RAV4",
                        "capacity": 1,
                        "attributes": [
                            {"label": "Transmission", "value": "Automatic"},
                            {"label": "Seats", "value": "5"},
                            {"label": "Fuel", "value": "Hybrid"},
                            {"label": "Drive", "value": "AWD"},
                            {"label": "Bags", "value": "4"},
                        ],
                    },
                    {
                        "name": "Unit S-3311",
                        "description": "Volkswagen Tiguan",
                        "capacity": 1,
                        "attributes": [
                            {"label": "Transmission", "value": "Automatic"},
                            {"label": "Seats", "value": "5"},
                            {"label": "Fuel", "value": "Diesel"},
                            {"label": "Drive", "value": "FWD"},
                            {"label": "Bags", "value": "4"},
                        ],
                    },
                    {
                        "name": "Unit S-3312",
                        "description": "Kia Sportage",
                        "capacity": 1,
                        "attributes": [
                            {"label": "Transmission", "value": "Manual"},
                            {"label": "Seats", "value": "5"},
                            {"label": "Fuel", "value": "Petrol"},
                            {"label": "Drive", "value": "FWD"},
                            {"label": "Bags", "value": "3"},
                        ],
                    },
                    {
                        "name": "Unit S-3313",
                        "description": "Mazda CX-5",
                        "capacity": 1,
                        "attributes": [
                            {"label": "Transmission", "value": "Automatic"},
                            {"label": "Seats", "value": "5"},
                            {"label": "Fuel", "value": "Petrol"},
                            {"label": "Drive", "value": "AWD"},
                            {"label": "Bags", "value": "4"},
                        ],
                    },
                ],
            },
            {
                "name": "Electric class",
                "description": "Zero-emission rentals with first-day charging included.",
                "slotDurationMinutes": 1440,
                "minSlotsPerBooking": 1,
                "maxSlotsPerBooking": 14,
                "priceMinorUnits": 6400,
                "cancellationCutoffHours": 48,
                "grid": {"daysBack": 28, "daysForward": 56, "startTimes": [{"hour": 0, "minute": 0}]},
                "resources": [
                    {
                        "name": "Unit E-9001",
                        "description": "Tesla Model 3",
                        "capacity": 1,
                        "attributes": [
                            {"label": "Range", "value": "491 km"},
                            {"label": "Seats", "value": "5"},
                            {"label": "Drive", "value": "RWD"},
                            {"label": "Charge", "value": "CCS"},
                        ],
                    },
                    {
                        "name": "Unit E-9002",
                        "description": "Hyundai Ioniq 5",
                        "capacity": 1,
                        "attributes": [
                            {"label": "Range", "value": "481 km"},
                            {"label": "Seats", "value": "5"},
                            {"label": "Drive", "value": "AWD"},
                            {"label": "Charge", "value": "CCS"},
                        ],
                    },
                    {
                        "name": "Unit E-9003",
                        "description": "Renault Zoe",
                        "capacity": 1,
                        "attributes": [
                            {"label": "Range", "value": "395 km"},
                            {"label": "Seats", "value": "5"},
                            {"label": "Drive", "value": "FWD"},
                            {"label": "Charge", "value": "Type 2"},
                        ],
                    },
                ],
            },
        ],
        "simpleService": {
            "name": "Standard class",
            "description": "A dependable mid-range car for everyday trips.",
            "slotDurationMinutes": 1440,
            "priceMinorUnits": 5200,
            "cancellationCutoffHours": 48,
            "minSlotsPerBooking": 1,
            "maxSlotsPerBooking": 14,
            "grid": {"daysBack": 7, "daysForward": 42, "startTimes": [{"hour": 0, "minute": 0}]},
            "resource": {
                "name": "Unit A-1",
                "description": "Opel Astra",
                "capacity": 1,
                "attributes": [
                    {"label": "Transmission", "value": "Manual"},
                    {"label": "Seats", "value": "5"},
                    {"label": "Fuel", "value": "Petrol"},
                    {"label": "Bags", "value": "3"},
                ],
            },
        },
    },
    "oneToOne": {
        "verticalId": "oneToOne",
        "bookingModel": "one_to_one",
        "currency": "EUR",
        "baseTz": "Europe/Warsaw",
        "categories": [
            {"id": "math", "label": "Maths & sciences"},
            {"id": "languages", "label": "Languages"},
            {"id": "music", "label": "Music"},
            {"id": "coding", "label": "Coding"},
            {"id": "exam", "label": "Exam prep"},
        ],
        "providers": [
            {
                "name": "Northline Tutoring",
                "tagline": "One-to-one, results-first",
                "bio": "A small studio of specialist tutors covering STEM and languages. Sessions are hourly, in person near the centre or online.",
                "categoryId": "math",
                "city": "Warsaw",
                "country": "Poland",
                "lat": 52.2297,
                "lng": 21.0122,
                "publicCode": "NORTH-1180",
                "rating": 4.9,
                "reviewCount": 214,
                "links": [{"label": "Website", "url": "https://example.com/northline"}],
            },
            {
                "name": "Verba Languages",
                "tagline": "Conversational fluency",
                "bio": "Native-speaker language coaching for adults and teens.",
                "categoryId": "languages",
                "city": "Kraków",
                "country": "Poland",
                "lat": 50.0647,
                "lng": 19.945,
                "publicCode": "VERBA-3320",
                "rating": 4.7,
                "reviewCount": 158,
                "links": [],
            },
            {
                "name": "Sono Music School",
                "tagline": "Piano, guitar, voice",
                "bio": "Instrument lessons for beginners through grade eight.",
                "categoryId": "music",
                "city": "Gdańsk",
                "country": "Poland",
                "lat": 54.352,
                "lng": 18.6466,
                "publicCode": "SONO-7745",
                "rating": 4.8,
                "reviewCount": 121,
                "links": [],
            },
            {
                "name": "Codeworks Mentors",
                "tagline": "Learn to ship code",
                "bio": "Practical programming mentorship in Python, JavaScript and SQL.",
                "categoryId": "coding",
                "city": "Wrocław",
                "country": "Poland",
                "lat": 51.1079,
                "lng": 17.0385,
                "publicCode": "CODE-2091",
                "rating": 4.6,
                "reviewCount": 89,
                "links": [],
            },
            {
                "name": "Apex Exam Prep",
                "tagline": "SAT · IB · Matura",
                "bio": "Targeted revision and mock exams with detailed feedback.",
                "categoryId": "exam",
                "city": "Poznań",
                "country": "Poland",
                "lat": 52.4064,
                "lng": 16.9252,
                "publicCode": "APEX-6612",
                "rating": 4.8,
                "reviewCount": 143,
                "links": [],
            },
            {
                "name": "Helix STEM",
                "tagline": "Maths, physics, chemistry",
                "bio": "University-level tutors for demanding science coursework.",
                "categoryId": "math",
                "city": "Kraków",
                "country": "Poland",
                "lat": 50.0619,
                "lng": 19.9368,
                "publicCode": "HELIX-4408",
                "rating": 4.5,
                "reviewCount": 67,
                "links": [],
            },
        ],
        "demoServices": [
            {
                "name": "Mathematics",
                "description": "Algebra, calculus and problem-solving with Ana.",
                "slotDurationMinutes": 60,
                "minSlotsPerBooking": 1,
                "maxSlotsPerBooking": 2,
                "priceMinorUnits": 6000,
                "cancellationCutoffHours": 24,
                "grid": {
                    "daysBack": 28,
                    "daysForward": 56,
                    "weekdays": [1, 2, 3, 4, 5],
                    "startTimes": [
                        {"hour": 9, "minute": 0},
                        {"hour": 10, "minute": 0},
                        {"hour": 11, "minute": 0},
                        {"hour": 13, "minute": 0},
                        {"hour": 14, "minute": 0},
                        {"hour": 15, "minute": 0},
                        {"hour": 16, "minute": 0},
                    ],
                },
                "resources": [
                    {
                        "name": "Ana Ruiz",
                        "description": "PhD in applied mathematics, 8 years tutoring.",
                        "capacity": 1,
                        "attributes": [
                            {"label": "Levels", "value": "GCSE → University"},
                            {"label": "Format", "value": "In person or online"},
                            {"label": "Languages", "value": "English, Polish"},
                        ],
                    },
                ],
            },
            {
                "name": "Physics",
                "description": "Mechanics, electromagnetism and lab report coaching.",
                "slotDurationMinutes": 60,
                "minSlotsPerBooking": 1,
                "maxSlotsPerBooking": 2,
                "priceMinorUnits": 6500,
                "cancellationCutoffHours": 24,
                "grid": {
                    "daysBack": 28,
                    "daysForward": 56,
                    "weekdays": [1, 2, 3, 4, 5],
                    "startTimes": [
                        {"hour": 9, "minute": 0},
                        {"hour": 10, "minute": 0},
                        {"hour": 11, "minute": 0},
                        {"hour": 13, "minute": 0},
                        {"hour": 14, "minute": 0},
                        {"hour": 15, "minute": 0},
                        {"hour": 16, "minute": 0},
                    ],
                },
                "resources": [
                    {
                        "name": "Jon Vekic",
                        "description": "MSc physics, examiner for the national board.",
                        "capacity": 1,
                        "attributes": [
                            {"label": "Levels", "value": "A-level → University"},
                            {"label": "Format", "value": "Online"},
                            {"label": "Languages", "value": "English"},
                        ],
                    },
                ],
            },
            {
                "name": "Exam prep",
                "description": "Structured revision with weekly mock papers.",
                "slotDurationMinutes": 60,
                "minSlotsPerBooking": 1,
                "maxSlotsPerBooking": 2,
                "priceMinorUnits": 7000,
                "cancellationCutoffHours": 24,
                "grid": {
                    "daysBack": 28,
                    "daysForward": 56,
                    "weekdays": [1, 2, 3, 4, 5],
                    "startTimes": [
                        {"hour": 9, "minute": 0},
                        {"hour": 10, "minute": 0},
                        {"hour": 11, "minute": 0},
                        {"hour": 13, "minute": 0},
                        {"hour": 14, "minute": 0},
                        {"hour": 15, "minute": 0},
                        {"hour": 16, "minute": 0},
                    ],
                },
                "resources": [
                    {
                        "name": "Priya Nair",
                        "description": "Specialist in Matura and IB mathematics.",
                        "capacity": 1,
                        "attributes": [
                            {"label": "Focus", "value": "Matura, IB"},
                            {"label": "Format", "value": "In person or online"},
                            {"label": "Languages", "value": "English, Polish"},
                        ],
                    },
                ],
            },
        ],
        "simpleService": {
            "name": "Introductory lesson",
            "description": "A first hour to assess level and set a plan.",
            "slotDurationMinutes": 60,
            "priceMinorUnits": 5000,
            "cancellationCutoffHours": 24,
            "minSlotsPerBooking": 1,
            "maxSlotsPerBooking": 1,
            "grid": {
                "daysBack": 7,
                "daysForward": 42,
                "weekdays": [1, 2, 3, 4, 5],
                "startTimes": [
                    {"hour": 9, "minute": 0},
                    {"hour": 10, "minute": 0},
                    {"hour": 11, "minute": 0},
                    {"hour": 13, "minute": 0},
                    {"hour": 14, "minute": 0},
                    {"hour": 15, "minute": 0},
                    {"hour": 16, "minute": 0},
                ],
            },
            "resource": {
                "name": "Lead tutor",
                "description": "Assigned on booking.",
                "capacity": 1,
                "attributes": [
                    {"label": "Format", "value": "In person or online"},
                    {"label": "Duration", "value": "60 min"},
                ],
            },
        },
    },
    "group": {
        "verticalId": "group",
        "bookingModel": "shared_capacity",
        "currency": "EUR",
        "baseTz": "Europe/Warsaw",
        "categories": [
            {"id": "vinyasa", "label": "Vinyasa"},
            {"id": "hatha", "label": "Hatha"},
            {"id": "pilates", "label": "Pilates"},
            {"id": "meditation", "label": "Meditation"},
            {"id": "strength", "label": "Strength"},
        ],
        "providers": [
            {
                "name": "Lotus Studio",
                "tagline": "Breathe, move, reset",
                "bio": "A light-filled studio in the old town offering daily classes for every level. Mats and props provided; walk-ins welcome when space allows.",
                "categoryId": "vinyasa",
                "city": "Warsaw",
                "country": "Poland",
                "lat": 52.2297,
                "lng": 21.0122,
                "publicCode": "LOTUS-5150",
                "rating": 4.9,
                "reviewCount": 402,
                "links": [
                    {"label": "Website", "url": "https://example.com/lotus"},
                    {"label": "Timetable", "url": "https://example.com/lotus/timetable"},
                ],
            },
            {
                "name": "Riverside Yoga",
                "tagline": "Hatha by the Vistula",
                "bio": "Slow, alignment-focused classes suitable for beginners.",
                "categoryId": "hatha",
                "city": "Kraków",
                "country": "Poland",
                "lat": 50.0647,
                "lng": 19.945,
                "publicCode": "RIVER-3380",
                "rating": 4.6,
                "reviewCount": 176,
                "links": [],
            },
            {
                "name": "Core Pilates Lab",
                "tagline": "Reformer & mat",
                "bio": "Small-group Pilates focused on strength and posture.",
                "categoryId": "pilates",
                "city": "Gdańsk",
                "country": "Poland",
                "lat": 54.352,
                "lng": 18.6466,
                "publicCode": "CORE-9925",
                "rating": 4.7,
                "reviewCount": 133,
                "links": [],
            },
            {
                "name": "Still Point",
                "tagline": "Guided meditation",
                "bio": "Drop-in mindfulness and breathwork sessions.",
                "categoryId": "meditation",
                "city": "Wrocław",
                "country": "Poland",
                "lat": 51.1079,
                "lng": 17.0385,
                "publicCode": "STILL-2044",
                "rating": 4.8,
                "reviewCount": 98,
                "links": [],
            },
            {
                "name": "Forge Strength",
                "tagline": "Small-group conditioning",
                "bio": "Coached strength circuits, capped at twelve per session.",
                "categoryId": "strength",
                "city": "Poznań",
                "country": "Poland",
                "lat": 52.4064,
                "lng": 16.9252,
                "publicCode": "FORGE-6710",
                "rating": 4.5,
                "reviewCount": 71,
                "links": [],
            },
            {
                "name": "Sunrise Vinyasa",
                "tagline": "Morning flows",
                "bio": "Energetic dawn classes to start the day.",
                "categoryId": "vinyasa",
                "city": "Kraków",
                "country": "Poland",
                "lat": 50.0619,
                "lng": 19.9368,
                "publicCode": "SUNRISE-4416",
                "rating": 4.7,
                "reviewCount": 154,
                "links": [],
            },
        ],
        "demoServices": [
            {
                "name": "Vinyasa Flow",
                "description": "A dynamic, breath-led flow for all levels.",
                "slotDurationMinutes": 60,
                "minSlotsPerBooking": 1,
                "maxSlotsPerBooking": 1,
                "priceMinorUnits": 1800,
                "cancellationCutoffHours": 12,
                "grid": {
                    "daysBack": 28,
                    "daysForward": 56,
                    "startTimes": [
                        {"hour": 7, "minute": 0},
                        {"hour": 9, "minute": 0},
                        {"hour": 12, "minute": 0},
                        {"hour": 17, "minute": 0},
                        {"hour": 18, "minute": 30},
                    ],
                },
                "resources": [
                    {
                        "name": "Studio A",
                        "description": "Main room, sprung floor, 12 mats.",
                        "capacity": 12,
                        "attributes": [
                            {"label": "Capacity", "value": "12 spots"},
                            {"label": "Level", "value": "All levels"},
                            {"label": "Heated", "value": "No"},
                        ],
                    },
                ],
            },
            {
                "name": "Hatha Basics",
                "description": "Slower, alignment-focused practice for beginners.",
                "slotDurationMinutes": 60,
                "minSlotsPerBooking": 1,
                "maxSlotsPerBooking": 1,
                "priceMinorUnits": 1600,
                "cancellationCutoffHours": 12,
                "grid": {
                    "daysBack": 28,
                    "daysForward": 56,
                    "startTimes": [
                        {"hour": 7, "minute": 0},
                        {"hour": 9, "minute": 0},
                        {"hour": 12, "minute": 0},
                    ],
                },
                "resources": [
                    {
                        "name": "Studio B",
                        "description": "Quiet room, 10 mats.",
                        "capacity": 10,
                        "attributes": [
                            {"label": "Capacity", "value": "10 spots"},
                            {"label": "Level", "value": "Beginner"},
                            {"label": "Heated", "value": "No"},
                        ],
                    },
                ],
            },
            {
                "name": "Candlelight Meditation",
                "description": "A restorative evening wind-down.",
                "slotDurationMinutes": 60,
                "minSlotsPerBooking": 1,
                "maxSlotsPerBooking": 1,
                "priceMinorUnits": 1400,
                "cancellationCutoffHours": 12,
                "grid": {
                    "daysBack": 28,
                    "daysForward": 56,
                    "startTimes": [{"hour": 20, "minute": 0}],
                },
                "resources": [
                    {
                        "name": "Studio A",
                        "description": "Main room, dimmed, bolsters provided.",
                        "capacity": 16,
                        "attributes": [
                            {"label": "Capacity", "value": "16 spots"},
                            {"label": "Level", "value": "All levels"},
                            {"label": "Props", "value": "Provided"},
                        ],
                    },
                ],
            },
        ],
        "simpleService": {
            "name": "Open class",
            "description": "A drop-in group session for every level.",
            "slotDurationMinutes": 60,
            "priceMinorUnits": 1500,
            "cancellationCutoffHours": 12,
            "minSlotsPerBooking": 1,
            "maxSlotsPerBooking": 1,
            "grid": {
                "daysBack": 7,
                "daysForward": 42,
                "startTimes": [
                    {"hour": 7, "minute": 0},
                    {"hour": 9, "minute": 0},
                    {"hour": 12, "minute": 0},
                ],
            },
            "resource": {
                "name": "Main room",
                "description": "Shared studio space.",
                "capacity": 12,
                "attributes": [
                    {"label": "Capacity", "value": "12 spots"},
                    {"label": "Level", "value": "All levels"},
                ],
            },
        },
    },
}
