/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The complete `domain.config.json` tree, after normalization.
 *
 * Every block is also overridable per service through
 * `services.metadata.<block>`, see `rules.effective_service_config`. The
 * service row wins over these globals.
 */
export interface DomainConfig {
  configVersion?: number;
  domain?: string;
  tenancy?: Tenancy;
  capabilities?: Capabilities;
  booking?: Booking;
  pricing?: Pricing;
  payments?: Payments;
  inventory?: Inventory;
  location?: Location;
  prerequisites?: Prerequisite[];
  timing?: Timing;
  recurrence?: Recurrence;
  entitlements?: Entitlements;
  discovery?: Discovery;
  terms?: Terms;
  copy?: Copy;
  metaFields?: MetaFields;
  rules?: LegacyRules;
  search?: LegacySearch;
}
export interface Tenancy {
  mode?: "single" | "multi";
  /**
   * Required when mode is 'single', how the app resolves its one business.
   */
  providerCode?: string | null;
  /**
   * Defaults to (mode == 'multi') at load: a marketplace onboards businesses, a single-business site does not.
   */
  selfOnboarding?: boolean | null;
  tenantVerification?: TenantVerification;
  commission?: Commission;
}
export interface TenantVerification {
  required?: boolean;
  credentials?: Credential[];
}
export interface Credential {
  key: string;
  label?: string | null;
  expires?: boolean | null;
  [k: string]: unknown;
}
export interface Commission {
  enabled?: boolean;
  rateBps?: number;
  chargedOn?: string;
}
/**
 * The on/off spine. A false capability means the UI hides the surface AND
 * the backend refuses the write, not one without the other.
 */
export interface Capabilities {
  payments?: boolean;
  inventory?: boolean;
  waitlist?: boolean;
  quotes?: boolean;
  recurrence?: boolean;
  prerequisites?: boolean;
  entitlements?: boolean;
  cart?: boolean;
  reviews?: boolean;
  follows?: boolean;
}
export interface Booking {
  unitKind?:
    | "time_slot"
    | "staff"
    | "asset"
    | "seat"
    | "room"
    | "class_capacity"
    | "stock_item"
    | "subscription_slot"
    | "project";
  granularity?: "minute" | "hour" | "day" | "night" | "week" | "month" | "none";
  duration?: Duration;
  party?: Party;
  sequence?: Sequence;
  subject?: Subject;
  options?: BookingOption[];
}
export interface Duration {
  mode?: "fixed" | "variable" | "customer_chosen" | "open_ended";
  minUnits?: number;
  maxUnits?: number;
  incrementUnits?: number;
}
export interface Party {
  mode?: "individual" | "group" | "buyout";
  min?: number;
  /**
   * null means the resource's own capacity is the ceiling.
   */
  max?: number | null;
  /**
   * Age bands and similar, each with its own priceFactor.
   */
  composition?: CompositionBand[] | null;
  matchResourceCapacity?: boolean;
}
export interface CompositionBand {
  key: string;
  label?: string | null;
  priceFactor?: number | null;
  [k: string]: unknown;
}
export interface Sequence {
  enabled?: boolean;
  steps?: number;
  minGapHours?: number;
  maxGapHours?: number | null;
}
export interface Subject {
  enabled?: boolean;
  noun?: string;
  fields?: SubjectField[];
}
export interface SubjectField {
  key: string;
  label?: string | null;
  type?: ("text" | "number" | "boolean" | "date" | "select" | "file") | null;
  required?: boolean | null;
  options?: string[] | null;
  helpText?: string | null;
  [k: string]: unknown;
}
export interface BookingOption {
  key: string;
  type?: "boolean" | "select";
  label?: string | null;
  priceMinorUnits?: number | null;
  /**
   * Required when type is 'select'.
   */
  choices?: OptionChoice[] | null;
  helpText?: string | null;
  [k: string]: unknown;
}
export interface OptionChoice {
  key: string;
  label?: string | null;
  priceMinorUnits?: number | null;
  requires?: string[] | null;
  [k: string]: unknown;
}
export interface Pricing {
  model?:
    "fixed" | "per_hour" | "per_person" | "per_unit" | "tiered" | "quote" | "deposit_balance" | "subscription" | "free";
  /**
   * A 3-letter ISO 4217 code.
   */
  currency?: string;
  currencyExponent?: number;
  rate?: Rate;
  secondaryRate?: Rate | null;
  tiers?: Tier[];
  /**
   * True reproduces the v1 formula (price x slots x party). False where the party shares one unit, a tennis court costs the same for 2 or 4.
   */
  chargePerPerson?: boolean;
  caps?: Caps;
  fees?: Fee[];
  deposit?: Deposit;
}
export interface Rate {
  per?: "booking" | "slot" | "hour" | "day" | "night" | "week" | "month" | "person" | "unit";
  amountMinorUnits?: number;
}
export interface Tier {
  key: string;
  amountMinorUnits: number;
  label?: string | null;
  quantityCap?: number | null;
  appliesWhen?: {
    [k: string]: unknown;
  } | null;
  validFrom?: string | null;
  validUntil?: string | null;
  [k: string]: unknown;
}
export interface Caps {
  perBookingMinorUnits?: number | null;
  /**
   * Declared but NOT enforced: it needs the customer's other bookings that day, which is a query, not arithmetic.
   */
  perDayMinorUnits?: number | null;
}
export interface Fee {
  key?: string | null;
  kind?: "flat" | "percent" | "distanceBand";
  label?: string | null;
  /**
   * For kind 'flat'.
   */
  amountMinorUnits?: number | null;
  /**
   * For kind 'percent'.
   */
  rateBps?: number | null;
  /**
   * Required, and non-empty, for kind 'distanceBand'.
   */
  bands?: DistanceBand[] | null;
  appliesWhen?: {
    [k: string]: unknown;
  } | null;
  [k: string]: unknown;
}
export interface DistanceBand {
  maxKm?: number | null;
  feeMinorUnits?: number;
  [k: string]: unknown;
}
export interface Deposit {
  enabled?: boolean;
  kind?: "percent" | "flat";
  value?: number;
  refundable?: boolean;
}
export interface Payments {
  flow?: "prepay" | "pay_on_site" | "invoice_after" | "split" | "none";
  payer?: "customer" | "third_party";
  schedule?: ScheduleStep[];
  billingCycle?: "none" | "weekly" | "monthly" | "annual";
  noShowFee?: NoShowFee;
  usageMetered?: boolean;
  /**
   * No PSP exists in this repo. 'manual' = the owner marks a booking paid.
   */
  adapter?: string;
}
export interface ScheduleStep {
  key: string;
  kind?: "percent" | "flat";
  value?: number;
  label?: string | null;
  relativeTo?: string | null;
  dueOffsetDays?: number | null;
  dueOffsetHours?: number | null;
  [k: string]: unknown;
}
/**
 * NOT YET ENFORCED, needs the payments layer (no payments table exists).
 */
export interface NoShowFee {
  enabled?: boolean;
  amountMinorUnits?: number;
}
export interface Inventory {
  mode?: "none" | "finite" | "rentable" | "consumable" | "serialised";
  reservationWindowMinutes?: number;
  loanPeriodHours?: number | null;
  returnRequired?: boolean;
  overdueFeePerDayMinorUnits?: number;
  restockCycle?: string;
  ratioConstraint?: {
    [k: string]: unknown;
  } | null;
}
export interface Location {
  modes?: ("on_site" | "at_customer" | "remote" | "delivery" | "pickup")[];
  default?: "on_site" | "at_customer" | "remote" | "delivery" | "pickup";
  /**
   * The business's own IANA timezone. Absent in v1, which is why an anonymous visitor always saw availability grouped in UTC.
   */
  timezone?: string;
  distanceUnit?: string;
  /**
   * The distance-from point.
   */
  origin?: Origin | null;
  serviceArea?: ServiceArea;
  remote?: Remote;
  fulfilment?: Fulfilment;
}
export interface Origin {
  city?: string | null;
  lat?: number | null;
  lng?: number | null;
  [k: string]: unknown;
}
export interface ServiceArea {
  radiusKm?: number | null;
  travelBufferMinutes?: number;
  feeBands?: DistanceBand[];
}
export interface Remote {
  meetingLinkMode?: string;
}
export interface Fulfilment {
  windowMinutes?: number;
  cutoffHoursBefore?: number;
}
export interface Prerequisite {
  key: string;
  kind: "id_check" | "licence" | "intake_form" | "waiver" | "membership" | "approval" | "credential";
  appliesTo?: "customer" | "tenant" | "subject";
  label?: string | null;
  required?: boolean | null;
  blocksConfirmation?: boolean | null;
  validityDays?: number | null;
  verifier?: string | null;
  fields?: PrereqField[] | null;
  [k: string]: unknown;
}
export interface PrereqField {
  key: string;
  label?: string | null;
  type?: ("text" | "number" | "boolean" | "date" | "select" | "file") | null;
  required?: boolean | null;
  [k: string]: unknown;
}
export interface Timing {
  confirmation?: "instant" | "request_approve";
  /**
   * NOT YET ENFORCED, auto-expiring a stale request needs a scheduled job.
   */
  approvalWindowHours?: number;
  leadTimeMinutes?: number;
  waitlist?: Waitlist;
  seasons?: DateWindow[];
  blackouts?: DateWindow[];
  slotDurationMinutes?: number;
  maxBookingsPerSlot?: number;
  cancellationWindowHours?: number;
  advanceBookingWindowDays?: number;
  bufferMinutes?: number;
}
export interface Waitlist {
  enabled?: boolean;
  autoPromote?: boolean;
  maxPerSlot?: number;
}
export interface DateWindow {
  startDate: string;
  endDate: string;
  key?: string | null;
  label?: string | null;
  [k: string]: unknown;
}
export interface Recurrence {
  enabled?: boolean;
  patterns?: ("weekly" | "biweekly" | "monthly")[];
  maxOccurrences?: number | null;
  term?: Term;
}
export interface Term {
  mode?: string;
  noticePeriodDays?: number;
}
export interface Entitlements {
  enabled?: boolean;
  kind?: "none" | "credits" | "membership" | "pass";
  plans?: Plan[];
}
export interface Plan {
  key: string;
  label?: string | null;
  credits?: number | null;
  cycle?: string | null;
  discountBps?: number | null;
  priceMinorUnits?: number | null;
  appliesToServices?: string[] | null;
  [k: string]: unknown;
}
export interface Discovery {
  mode?: "browse" | "reverse";
  facets?: DiscoveryFacets;
  matching?: Matching;
}
export interface DiscoveryFacets {
  price?: boolean;
  distance?: boolean;
  rating?: boolean;
  availability?: boolean;
  unitKind?: boolean;
}
export interface Matching {
  enabled?: boolean;
  source?: string;
}
/**
 * Every noun the UI renders. All 17 keys are required to be non-empty
 * strings, the frontend's `<Term>` has nothing to fall back to.
 */
export interface Terms {
  provider?: string;
  providers?: string;
  service?: string;
  services?: string;
  staff?: string;
  subject?: string;
  party?: string;
  resource?: string;
  resources?: string;
  slot?: string;
  slots?: string;
  booking?: string;
  bookings?: string;
  client?: string;
  clients?: string;
  admin?: string;
  admins?: string;
}
export interface Copy {
  landingTitle?: string;
  landingSubtitle?: string;
  confirmTitle?: string;
  emptyStateSlots?: string;
  emptyStateBookings?: string;
  requestPending?: string;
  waitlistJoined?: string;
  quoteRequested?: string;
  depositDue?: string;
  prerequisiteBlocked?: string;
}
/**
 * Custom fields per entity. Adding one needs no migration, the values land
 * in that table's `metadata` jsonb column.
 */
export interface MetaFields {
  providers?: MetaField[];
  services?: MetaField[];
  resources?: MetaField[];
  slots?: MetaField[];
  bookings?: MetaField[];
  subjects?: MetaField[];
}
export interface MetaField {
  key: string;
  /**
   * 'string' is accepted as an alias for 'text', it shipped in domain.config.json and matched nothing in the v1 validator.
   */
  type: ("text" | "number" | "boolean" | "date" | "select" | "file") | "string";
  label?: string | null;
  required?: boolean | null;
  options?: string[] | null;
  [k: string]: unknown;
}
/**
 * @deprecated
 * DEPRECATED. `timing` owns these five keys; `normalize()` mirrors them back
 * here so a v1 reader and a v1 config file both keep working.
 */
export interface LegacyRules {
  slotDurationMinutes?: number;
  maxBookingsPerSlot?: number;
  cancellationWindowHours?: number;
  advanceBookingWindowDays?: number;
  bufferMinutes?: number;
}
/**
 * @deprecated
 * DEPRECATED. `discovery` owns this; `normalize()` keeps the two in sync.
 */
export interface LegacySearch {
  facets?: LegacySearchFacets;
}
export interface LegacySearchFacets {
  price?: boolean;
  distance?: boolean;
  rating?: boolean;
}
