import type { MockStore } from "@/api/storeTypes";
import { assembleStore, type VerticalSeedConfig } from "@/api/seed/common";

/**
 * Fleet vertical: many distinct units, one bookable at a time each, multi-day
 * ranges. Mapped to the `unit_selection` booking model. Day-length slots
 * (1440 min) so a booking spans whole calendar days; ranges up to 14 days.
 */

const FULL_DAY = [{ hour: 0, minute: 0 }];

const config: VerticalSeedConfig = {
  verticalId: "fleet",
  bookingModel: "unit_selection",
  currency: "EUR",
  baseTz: "Europe/Warsaw",
  categories: [
    { id: "economy", label: "Economy" },
    { id: "suv", label: "SUV" },
    { id: "van", label: "Van" },
    { id: "electric", label: "Electric" },
    { id: "luxury", label: "Luxury" },
  ],
  providers: [
    {
      name: "Vistula Auto",
      tagline: "City rentals, no queues",
      bio: "Family-run rental desk two minutes from Warsaw Central. Same-day pickup, transparent pricing, and a fleet kept under three years old.",
      categoryId: "economy",
      city: "Warsaw",
      country: "Poland",
      lat: 52.2297,
      lng: 21.0122,
      publicCode: "VISTULA-4471",
      rating: 4.7,
      reviewCount: 318,
      links: [
        { label: "Website", url: "https://example.com/vistula" },
        { label: "Terms", url: "https://example.com/vistula/terms" },
      ],
    },
    {
      name: "Nord Fleet",
      tagline: "Coastal SUVs & 4x4s",
      bio: "Rugged vehicles for the Tricity and beyond. Roof boxes and child seats included on request.",
      categoryId: "suv",
      city: "Gdańsk",
      country: "Poland",
      lat: 54.352,
      lng: 18.6466,
      publicCode: "NORD-2210",
      rating: 4.5,
      reviewCount: 142,
    },
    {
      name: "Kraków Renta",
      tagline: "Budget cars, old-town pickup",
      bio: "Economy hatchbacks collected steps from the Kazimierz district.",
      categoryId: "economy",
      city: "Kraków",
      country: "Poland",
      lat: 50.0647,
      lng: 19.945,
      publicCode: "KRK-8890",
      rating: 4.3,
      reviewCount: 96,
    },
    {
      name: "Odra Motors",
      tagline: "Vans & movers",
      bio: "Cargo and passenger vans for house moves and crew transport.",
      categoryId: "van",
      city: "Wrocław",
      country: "Poland",
      lat: 51.1079,
      lng: 17.0385,
      publicCode: "ODRA-5560",
      rating: 4.6,
      reviewCount: 74,
    },
    {
      name: "Baltic EV",
      tagline: "All-electric fleet",
      bio: "Zero-emission rentals with free charging on the first day.",
      categoryId: "electric",
      city: "Gdańsk",
      country: "Poland",
      lat: 54.372,
      lng: 18.638,
      publicCode: "BALT-7788",
      rating: 4.8,
      reviewCount: 205,
    },
    {
      name: "Piast Cars",
      tagline: "Executive & luxury",
      bio: "Premium saloons with chauffeur option for business travel.",
      categoryId: "luxury",
      city: "Poznań",
      country: "Poland",
      lat: 52.4064,
      lng: 16.9252,
      publicCode: "PIAST-3301",
      rating: 4.9,
      reviewCount: 61,
    },
    {
      name: "Tatra Wheels",
      tagline: "Mountain-ready SUVs",
      bio: "Winter tyres as standard from October. Ski racks available.",
      categoryId: "suv",
      city: "Kraków",
      country: "Poland",
      lat: 50.0619,
      lng: 19.9368,
      publicCode: "TATRA-6642",
      rating: 4.4,
      reviewCount: 88,
    },
  ],
  demoServices: [
    {
      name: "Compact class",
      description: "Nimble city cars — easy to park, light on fuel.",
      slotDurationMinutes: 1440,
      minSlotsPerBooking: 1,
      maxSlotsPerBooking: 14,
      priceMinorUnits: 4200,
      cancellationCutoffHours: 48,
      grid: { daysBack: 28, daysForward: 56, startTimes: FULL_DAY },
      resources: [
        {
          name: "Unit C-4471",
          description: "Volkswagen Polo",
          capacity: 1,
          attributes: [
            { label: "Transmission", value: "Manual" },
            { label: "Seats", value: "5" },
            { label: "Fuel", value: "Petrol" },
            { label: "Doors", value: "5" },
            { label: "Bags", value: "2" },
          ],
        },
        {
          name: "Unit C-4472",
          description: "Toyota Yaris",
          capacity: 1,
          attributes: [
            { label: "Transmission", value: "Automatic" },
            { label: "Seats", value: "5" },
            { label: "Fuel", value: "Hybrid" },
            { label: "Doors", value: "5" },
            { label: "Bags", value: "2" },
          ],
        },
        {
          name: "Unit C-4473",
          description: "Škoda Fabia",
          capacity: 1,
          attributes: [
            { label: "Transmission", value: "Manual" },
            { label: "Seats", value: "5" },
            { label: "Fuel", value: "Diesel" },
            { label: "Doors", value: "5" },
            { label: "Bags", value: "3" },
          ],
        },
        {
          name: "Unit C-4474",
          description: "Ford Fiesta",
          capacity: 1,
          attributes: [
            { label: "Transmission", value: "Manual" },
            { label: "Seats", value: "5" },
            { label: "Fuel", value: "Petrol" },
            { label: "Doors", value: "3" },
            { label: "Bags", value: "2" },
          ],
        },
        {
          name: "Unit C-4475",
          description: "Hyundai i20",
          capacity: 1,
          attributes: [
            { label: "Transmission", value: "Automatic" },
            { label: "Seats", value: "5" },
            { label: "Fuel", value: "Petrol" },
            { label: "Doors", value: "5" },
            { label: "Bags", value: "2" },
          ],
        },
      ],
    },
    {
      name: "SUV class",
      description: "Higher ride, more boot space, all-weather grip.",
      slotDurationMinutes: 1440,
      minSlotsPerBooking: 1,
      maxSlotsPerBooking: 14,
      priceMinorUnits: 7500,
      cancellationCutoffHours: 48,
      grid: { daysBack: 28, daysForward: 56, startTimes: FULL_DAY },
      resources: [
        {
          name: "Unit S-3310",
          description: "Toyota RAV4",
          capacity: 1,
          attributes: [
            { label: "Transmission", value: "Automatic" },
            { label: "Seats", value: "5" },
            { label: "Fuel", value: "Hybrid" },
            { label: "Drive", value: "AWD" },
            { label: "Bags", value: "4" },
          ],
        },
        {
          name: "Unit S-3311",
          description: "Volkswagen Tiguan",
          capacity: 1,
          attributes: [
            { label: "Transmission", value: "Automatic" },
            { label: "Seats", value: "5" },
            { label: "Fuel", value: "Diesel" },
            { label: "Drive", value: "FWD" },
            { label: "Bags", value: "4" },
          ],
        },
        {
          name: "Unit S-3312",
          description: "Kia Sportage",
          capacity: 1,
          attributes: [
            { label: "Transmission", value: "Manual" },
            { label: "Seats", value: "5" },
            { label: "Fuel", value: "Petrol" },
            { label: "Drive", value: "FWD" },
            { label: "Bags", value: "3" },
          ],
        },
        {
          name: "Unit S-3313",
          description: "Mazda CX-5",
          capacity: 1,
          attributes: [
            { label: "Transmission", value: "Automatic" },
            { label: "Seats", value: "5" },
            { label: "Fuel", value: "Petrol" },
            { label: "Drive", value: "AWD" },
            { label: "Bags", value: "4" },
          ],
        },
      ],
    },
    {
      name: "Electric class",
      description: "Zero-emission rentals with first-day charging included.",
      slotDurationMinutes: 1440,
      minSlotsPerBooking: 1,
      maxSlotsPerBooking: 14,
      priceMinorUnits: 6400,
      cancellationCutoffHours: 48,
      grid: { daysBack: 28, daysForward: 56, startTimes: FULL_DAY },
      resources: [
        {
          name: "Unit E-9001",
          description: "Tesla Model 3",
          capacity: 1,
          attributes: [
            { label: "Range", value: "491 km" },
            { label: "Seats", value: "5" },
            { label: "Drive", value: "RWD" },
            { label: "Charge", value: "CCS" },
          ],
        },
        {
          name: "Unit E-9002",
          description: "Hyundai Ioniq 5",
          capacity: 1,
          attributes: [
            { label: "Range", value: "481 km" },
            { label: "Seats", value: "5" },
            { label: "Drive", value: "AWD" },
            { label: "Charge", value: "CCS" },
          ],
        },
        {
          name: "Unit E-9003",
          description: "Renault Zoe",
          capacity: 1,
          attributes: [
            { label: "Range", value: "395 km" },
            { label: "Seats", value: "5" },
            { label: "Drive", value: "FWD" },
            { label: "Charge", value: "Type 2" },
          ],
        },
      ],
    },
  ],
  simpleService: {
    name: "Standard class",
    description: "A dependable mid-range car for everyday trips.",
    slotDurationMinutes: 1440,
    minSlotsPerBooking: 1,
    maxSlotsPerBooking: 14,
    priceMinorUnits: 5200,
    cancellationCutoffHours: 48,
    grid: { daysBack: 7, daysForward: 42, startTimes: FULL_DAY },
    resource: {
      name: "Unit A-1",
      description: "Opel Astra",
      capacity: 1,
      attributes: [
        { label: "Transmission", value: "Manual" },
        { label: "Seats", value: "5" },
        { label: "Fuel", value: "Petrol" },
        { label: "Bags", value: "3" },
      ],
    },
  },
};

export function seedFleet(): MockStore {
  return assembleStore(config);
}
